name: Production Deployment

on:
  push:
    branches:
      - main
      
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create .env file from secrets
        run: |
          echo "SNYK_TOKEN=${{ secrets.SNYK_TOKEN }}" > backend/.env

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_LOGIN }}/tp-devops-backend:latest